version: '3'

services:
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: jerry.martins
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress
      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: WebFlux!@2019!
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    container_name: mongo
    image: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: WebFlux!@2019!
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    networks:
      - mongo-compose-network

  #  spring:
  #    image: maven:3.6.1-jdk-11-slim
  #    container_name: spring
  #    working_dir: /spring
  #    volumes:
  #      - ./:/spring
  #    ports:
  #      - 8080:8080
  #    command: mvn clean test spring-boot:run
  #    depends_on:
  #      - mongo

networks:
  mongo-compose-network:
    driver: bridge